# Generated by Django 4.2.13 on 2024-06-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('min_price_threshold', models.FloatField(blank=True, null=True)),
                ('max_price_threshold', models.FloatField(blank=True, null=True)),
                ('tracking_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notification_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investmentasset')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_action', models.CharField(blank=True, max_length=10, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investmentasset')),
            ],
        ),
        migrations.RemoveField(
            model_name='pricetunnel',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='PriceTunnel',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
