# Generated by Django 4.2.13 on 2024-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_investmentasset_notificationsetting_pricerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
